tasks:
  - Go to the table with brown cups.
  - From the table with brown cups, go to the table with a black cloth.
  - Go to the table with red cups.
  - From the table with red cups, go to the table with a black cloth.
  - Go to the table with a sandwich.
  - From the table with a sandwich, go to the table with a black cloth.
  - Go to the table with a white jug.
  - From the table with a white jug, go to the table with a black cloth.